services:
  mongo:
    image: mongo:8.0
    container_name: tc6-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - tc6-mongo-data:/data/db

volumes:
  tc6-mongo-data:
